# docs/openapi.yaml

openapi: 3.1.0
info:
  version: 1.0.0
  title: Psychologist app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of psychologist app
tags:
  - name: Psychologists
    description: Operations about psychologists.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://pshyhologists.service.api
  - url: /
paths:
  /pshyhologists:
    get:
      $ref: ../swagger/paths/psychologists/get.yaml
    post:
      $ref: ../swagger/paths/psychologists/post.yaml
  /pshyhologists/{id}:
    get:
      $ref: ../swagger/paths/psychologists/{id}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
