# docs/openapi.yaml

openapi: 3.1.0
info:
  version: 1.0.0
  title: Psychologist app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of psychologist app
tags:
  - name: Psychologists
    description: Operations about psychologists.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://psy—Åhologists.service.api
  - url: /
paths:
  /psychologists:
    get:
      $ref: ../swagger/paths/psychologists/get.yaml
    post:
      $ref: ../swagger/paths/psychologists/post.yaml
  /psychologists/{id}:
    get:
      $ref: ../swagger/paths/psychologists/{id}/get.yaml
    put:
      $ref: ../swagger/paths/psychologists/{id}/put.yaml
    patch:
      $ref: ../swagger/paths/psychologists/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/psychologists/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.post.yaml
  /auth/me:
    get:
      $ref: ../swagger/paths/auth/me.get.yaml
components:
  securitySchemes:
    $ref: ../swagger/components/schemas/securitySchemes.yaml
